### ISSUE TITLE
Learned Kernels

### ISSUE THREAD

**Issue by bionicles** [CyberZHG/tf-keras-kervolution-2d#1]
**Is your feature request related to a problem? Please describe.**
we are not clear how to convolve a Keras Model as the kernel function

**Describe the solution you'd like**
we want to be able to apply a Keras Model as the kernel

**Describe alternatives you've considered**
split and vectorized_map at runtime

**Additional context**
vectorized_map doesn't like to use Graph tensors

**Comment by CyberZHG** [comment]
The kernels in this repo are `Layer`s, and `Model` inherits `Layer`.
